M48
; DRILL file {KiCad 9.0.7} date 2026-02-26T22:40:01-0500
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-02-26T22:40:01-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0728
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0866
%
G90
G05
T1
X3.8346Y-3.5338
X3.8346Y-3.7247
T2
X3.7153Y-3.522
X3.7153Y-3.7365
M30
